/**
 * Kinetic Smart API
 * Kinetic Smart Swagger Implementatin
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@citypay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.citypay.pos.kinetic.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class BatteryResponse {
  
  @SerializedName("success")
  private Boolean success = null;
  @SerializedName("charging")
  private Boolean charging = null;
  @SerializedName("percentage")
  private Integer percentage = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getSuccess() {
    return success;
  }
  public void setSuccess(Boolean success) {
    this.success = success;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getCharging() {
    return charging;
  }
  public void setCharging(Boolean charging) {
    this.charging = charging;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPercentage() {
    return percentage;
  }
  public void setPercentage(Integer percentage) {
    this.percentage = percentage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatteryResponse batteryResponse = (BatteryResponse) o;
    return (this.success == null ? batteryResponse.success == null : this.success.equals(batteryResponse.success)) &&
        (this.charging == null ? batteryResponse.charging == null : this.charging.equals(batteryResponse.charging)) &&
        (this.percentage == null ? batteryResponse.percentage == null : this.percentage.equals(batteryResponse.percentage));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.success == null ? 0: this.success.hashCode());
    result = 31 * result + (this.charging == null ? 0: this.charging.hashCode());
    result = 31 * result + (this.percentage == null ? 0: this.percentage.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatteryResponse {\n");
    
    sb.append("  success: ").append(success).append("\n");
    sb.append("  charging: ").append(charging).append("\n");
    sb.append("  percentage: ").append(percentage).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
