/**
 * Kinetic Smart API
 * Kinetic Smart Swagger Implementatin
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@citypay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.citypay.pos.kinetic.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class PingResponse {
  
  @SerializedName("ping")
  private Boolean ping = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getPing() {
    return ping;
  }
  public void setPing(Boolean ping) {
    this.ping = ping;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PingResponse pingResponse = (PingResponse) o;
    return (this.ping == null ? pingResponse.ping == null : this.ping.equals(pingResponse.ping));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.ping == null ? 0: this.ping.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PingResponse {\n");
    
    sb.append("  ping: ").append(ping).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
